#+Setupfile: /home/cpsoz/OrgT/odt.org
* Fitoride -- Anwendung und App für das statische Bike-Fitting

*Autor*: Ilja Papilloud, Elisabeth-Gymnasium Halle (Saale), Klasse 9d

** Einleitung

Nach dem statistischem Bundesamt /Destatis/ auf der Grundlage von Zahlen der Datenbank für EU-Statistiken /Eurostat/ (Stand 2019) fahren in Europa im Durchschnitt 24% der Europäer ab 15 Jahren Fahrrad (vgl. Statistisches Bundesamt /Destatis/, 2022a). Dabei ist die Niederlande mit rund 61% der Bevölkerung ab 15 Jahren, die Fahrrad fährt, ganz vorne. Es folgen Dänemark (47,5%), Finnland (38,8%), Ungarn (35,9%) und Slowenien (35,5%). Deutschland ist auf Platz sechs mit einem Anteil von rund 34% der Bevölkerung ab 15 Jahren, die Fahrrad fährt. Diese Zahlen unterscheiden sich nicht zwischen Männern und Frauen, wenn man die Statistik des Mobilitätsverhaltens von Männern und Frauen berücksichtigt, die auf den Zahlen von 2019 des /Eurobarometers 495/ basiert und alle 28 europäischen Länder betrifft (Statistisches Bundesamt /Destatis/, 2022b).

Eine neue Studie vom Bundesministerium für Verkehr und digitale Infrastruktur zeigt, dass durch die Covid-Pandemie, das Fahrrad an Popularität in Deutschland stark gewonnen hat (Bundesministerium für Verkehr und digitale Infrastruktur, 2021). Nach dieser Studie ist "Das Fahrrad bzw. Pedelec [...] im Verkehrsmittelvergleich das Fortbewegungsmittel mit dem höchsten Wachstumspotential. In Zukunft wollen es 41 Prozent der Menschen im Alter zwischen 14 und 69 Jahren häufiger nutzen" (ebd., 7). Wenn 77% der befragten Personen das Fahrrad zumindest selten fahren, fahren 38% der befragten Personen mit dem Fahrrad regelmäßig (ebd., 8). Alle befragten Personen benutzen das Fahrrad sowohl als Verkehrsmittel als auch in der Freizeit. Das Fahrrad wird von diesen Personen für seine gesundheitliche Aspekten und für den Spassfaktor erwähnt, und er positioniert sich unmittelbar hinter der Fortbewegung zu Fuß, die für die befragten Personen die größte Bedeutung im Bezug auf Gesundheit und Spaß hat.

Fahrradfahren als Form der sanften räumlichen Mobilität wird also neben der Fortbewegung zu Fuß in Deutschland stark unterstützt. Wie die Fortbewegung zu Fuß ist das Fahrradfahren umweltfreundlich (keine CO2 Emissionen, kaum Lärm), und es stellt sich deshalb als ein Verkehrsmittel für die Mikro- bis Mesomobilität dar, darin der Bund im Rahmen des Klimaschutzprogrammes 2030 stark investiert. Insbesondere die Radinfrastruktur soll im Rahmen dieses Programms weiter in der Stadt und auf dem Land ausgebaut werden, damit Fahrradfahrer bequemer und sicherer mit dem Fahrrad unterwegs sein können (Bundesministerium für Digitales und Verkehr, 2021). Diese Entwicklung dient nicht zuletzt der Gesundheit von Menschen, die Fahrrad fahren (vgl. World Health Organisation, 2018), selbst wenn in diesem Bereich die Aussage nach der, Fahrrad fahren die menschliche Gesundheit verbessern würde, nur im Allgemeinen zutrifft.

Im Besonderen zeigen etwa Oja et al. in ihrer Rezension von 16 spezifischen wissenschaftlichen Untersuchungen zur Verbindung zwischen Fahrradfahren und Gesundheit, dass diese Studien tatsächlich eine allgemeine positive Beziehung zwischen Fahrradfahren und Gesundheit insbesondere in Verbindung mit einem besseren Körper-Fitness wie etwa mit einer besseren Beweglichkeit oder mit Gewichtsabnahme zeigen (etwa Møller et al., 2011). Dagegen sind die gesundheitlichen Vorteile vom Fahrradfahren im kardiovaskulären Bereich mittelmäßig, und sie können im Bezug auf die Vorbeugung von Schwerkrankheiten wie Krebs oder degenerativen Krankheiten nicht eindeutig gezeigt werden (Oja et al., 2011). Eine Studie von Bourne, die wie Oja die spezifische Literatur im Bereich Gesundheit und Fahrradfahren mit elektrischem Antrieb auswertet, kommt zu dem Schluß, dass die physische Aktivität mit einem Pedelec im Vergleich zum Fahren von einem Fahrrad ohne elektrischen Antrieb keine eindeutige Vorteile weder für die Verbesserung des kardiovaskulären Systems, noch für die Vorbeugung von Schwerkrankheiten, noch für die Verbesserung der psychologischen Gesundheit bringt (Bourne et al., 2018). Dennoch gibt es in diesem Bereich keinen eindeutigen Beweis, dass Fahrradfahren mehr Vorteile als Pedelec fahren bringen würde, weil es nicht eindeutig belegt werden kann, dass eine gesteigerte physische Aktivität bzw. eine sportliche Aktivität mehr Vorteile im Vergleich zu einer weniger intensiven physischen Aktivität bringen würde (Blair et al., 2001).

Im Bereich dieser Literatur zu den möglichen gesundheitlichen Vorteilen, die das Fahrradfahren bringen würde, ist seit dem Ende der 1990 Jahre eine Literatur zu den physischen Schäden entstanden, die das Fahrradfahren verursachen kann, wenn das gefahrene Fahrrad zu klein oder zu groß ist, oder wenn die Position vom Fahrer auf dem Fahrrad falsch ist und unterschiedliche Schmerzen in den Knien, der Hüfte, dem Rücken und dem Nacken verursacht (etwa Bailey et al., 2003; Callaghan, 2005). Diese Literatur betrifft respektive die Bereiche des Bike-Sizing und des Bike-Fitting, und im Rahmen dieses Forschungsprojektes interessiert uns die Literatur zu Bike-Fitting bzw. zur Position vom Fahrradfahrer auf seinem Fahrrad.

** Bike-Fitting. Eine nicht exakte Wissenschaft

Bike-Fitting ist trotz der zahlreichen Untersuchungen, die in diesem Bereich vorgenommen wurden, keine exakte Wissenschaft, sondern eine experimentelle Wissenschaft, dass vom statistischen zu dynamischen Bike-Fitting und vom reinen experimentellen Wissen aus Erfahrung zu KI und video-unterstützten Techniken der Vermessung von Bewegungen auf dem Fahrrad reihen (etwa Holliday et al., 2017; Holliday, 2019). Die Studien, die in diesem Bereich zur Verfügung stehen und von der Sportmedizin, der Physiotheraphie bis zur Biomechanik und Kinematik reichen, kommen zum gemeinsamen Schluß, dass es trotz Fortschritte, die im Bereich des Bike-Fitting besonders durch die vielen Expermimenten erzielt und erreicht worden sind, keine einzige Methode für ein Bike-Fitting und kein perfektes Ergebnis aus einem Bike-Fitting gibt. Bike-Fitting trägt zwar zur Verbesserung der Position vom Fahrer auf dem Fahrrad entweder in der Variante des statischen oder des dynamischen Bike-Fitting bei. Aber das perfekte Bike-Fitting gibt es nicht und wird es wahrscheinlich aufgrund der unzähligen unterschiedlichen körperlichen Merkmalen bei Menschen, vom unterschiedlichen Fahrstyle der Fahrer und der Entwicklung von diesem Fahrstyle bei Einzelfahrern in der Zeit nie geben (etwa García-López, 2016).

Nichtsdestotrotz und wie die Studien zu Bike-Fitting zeigen, ist es möglich durch die Messung von menschlichen Körpermerkmalen und Winkeln die ideale Position für ein Fahrradfahrer in Bezug auf ein gegebenes Fahrrad zu schätzen, und diese Position in der Zeit und durch regelmäßigen Justierung, die insbesondere für professionelle Fahrer auch mit bestimmten physischen Übung und mit Physiotherapie verbunden werden, zu optimieren. In diesem Zusammenhang sind eine große Anzahl an Methoden und Verfahren entwickelt worden, die zur Dekonstruktion von einigen Mythen im Bereich des Bike-Fitting geführt haben, die Mittlerweile eine Anwendung von gender-neutralen Kriterien und Messungen für Menschen ab 15 Jahren unterstützen, davon einige auch sowohl im Kontext vom dynamischen als auch vom statischen Bike-Fitting gelten (vgl. Bini und Hume, 2016).

Daraus ergibt sich das Ziel dieser Forschung. Es besteht darin, eine einfache freie und kostenlose Anwendung für statisches Bike-Fitting auf der Grundlage dieser Literatur zu veröffentlichen, die in wenigen Stufen und in weniger Zeit einen guten bis sehr guten Start auf dem Fahrrad für jeden Fahrer/jede Fahrerin anbietet.

Abgesehen vom Bike-Fitting, die von erfahrenen Mitarbeitern in Fahrradgeschäften oder von Unternehmen als Dienstleistung gegen einen manchmal auch hohen Preis angeboten wird (vgl. etwa das beliebte Unternehmen für Bike-Fitting MyVeloFit: https://www.myvelofit.com/pricing), gibt es kaum kostenlose Alternativen. App für IOS und Android für das eigene durchgeführt Bike-Fitting existieren, selbst wenn sie selten sind. In unserer Forschung haben wir eine App "Bike Fast Fit" gefunden, die darin besteht, ein Bild mit dem Smartphone vom Fahrer auf seinem Fahrrad oder ein Film davon zu machen, daraus unterschiedliche Messungen produziert werden, um ein Fitting der optimalen Position vom Fahrer auf dem Fahrrad zu ermitteln (vgl. https://apps.apple.com/de/app/bike-fast-fit-elite/id1145619812; https://play.google.com/store/apps/details?id=at.steinbacher.posiclist). Diese App, die für Android Grundlagemessungen ermittelt, die manchmal von Daten aus der Literatur mehr oder weniger stark abweichen, und die für IOS in unterschiedlichen Version je Funktion bezahlt werden muss (https://apps.apple.com/de/app/bike-fast-fit-elite/id1145619812), die die App bietet, setzt das Kleben von Kontaktpunkten auf dem Körper, um die Messungen durchzuführen. Dies führt häufig zu Unregelmäßigkeiten bei der Messung je nachdem, wie gut die Kontaktpunkte geklebt wurden.

Abgesehen vom Geldfaktor ist die Verwendung dieser App oft aufwändig -- ein Smartphone oder ein Kamera muss lateral und parallel vom Fahrer stabil montiert werden. Die Person muss das Gerät aktivieren und er muss während einer Zeitlang (von 10 bis 20 Minuten) auf einem Fahrrad-Heimtrainer trainieren, um Daten zu generieren, die dann mehr oder weniger präzise sind bzw. davon der Vorteil im Vergleich zu einem traditionellen Bike-Fitting mit einfacheren Maßnahmen nicht eindeutig ist. Anders gesagt, ist diese Lösung für ein Bike-Fitting mit wenigem Aufwand (nicht jeder hat einen Fahrrad-Heimtrainer zu Hause) nicht ideal, und sie kommt im Fall vom gelegentlichen Fahren oder vom Fahrradfahren-on-the-go nicht in Frage.

Dagegen kann eine einfachere App ohne Verwendung von Kamera, Bildern, Filmen, 3D Abbildungen, Sensoren oder Fahrrad-Heimtrainer eine zufriedenstellende Bike-Fitting-Lösung anbieten, die nicht nur kostenlos ist, sondern verdichtete Ergebnisse aus der spezialisierten Literatur berücksichtigt, um eine optimale Position des Fahrers auf dem Fahrrad zu ermitteln. Dies ist die Grundidee der Fitoride-App, die ein Bike-Fitting in wenigen Minuten zu Hause oder on-the-go ohne spezielles Material kostenlos und transparent anbietet. Die App brauche dafür folgende Messungen: Innenbein des Fahrers/der Fahrerin, Winkel des Sattelrohrs, Länge des Sattels und Länge ab der Mitte des Sattels bis zur Mitte der Lenkerstange. Sie ermittelt:

  - die optimale Sitzhöhe auf dem Fahrrad
  - die Sattelposition (vorne oder hinten auf dem Sattelrohr)
  - die Position des Lenkers in der Relation zur Sitzposition
  - Ratschläge zur Optimierung dieses Settings

Aus der Literatur zu Bike-Fitting, die sich am meisten mit Messungen und Winkeln des Unterkörpers beschäftigt, ergibt sich, dass ein Bike-Fitting vom Fuß, zum Knie, zu der Hüfte, zum Schulter und zu den Armen des Fahrers gehen muss, um optimale Messungen zur optimalen Position des Fahrers auf dem Fahrrad ermitteln zu können. Entsprechend ist die App strukturiert, und sie berücksichtigt zuerst die Füße und die Pedalen.

*** Fuss und Pedalen

Der Blog vom /Cam's Cycling Collective/ (https://neillsbikefit.com.au) ist deshalb wertvoll, weil er die unterschiedlichen Mythen dekonstruiert, die mit dem Bike-Fitting verbunden sind und auf zahlreiche Video im Internet von manchmal sehr erfahrenen Sportlern weiter transportiert werden.

Ein erster Mythos betrifft die Position vom Fuss auf dem Pedal insbesondere im Fall vom Fahrradfahren mit Klickpedalen (vgl. insb. https://neillsbikefit.com.au/?page_id=348). Häufig wird erzählt, dass der vordere Drittel des Fusses auf dem Pedal drucken muss, damit die meiste Kraft auf die Pedalen befreit wird und das Fahren mit dem Fahrrad beschleunigt wird. Diese Position vom Fuß auf dem Pedal kann im Fall von Klickpedalen am besten eingeschätzt werden, weil die Bindung aus Plastik oder aus Metall an der Sohle des Schuhes genau geregelt werden kann, um die optimale Position zu erreichen, die erlaubt, mehr Kraft in die Bewegung auf die Pedalen auzuüben.

Lange galt, dass diese Bindungen an der Schnittstelle zwischen dem zweiten Metatarsalknochen und dem Halux positioniert werden sollten. Diese Idee kam jedoch von einer Übertragung der Biomechanik des Fußes beim Gehen auf das Fahrradfahren. Auf dem Fahrrad sieht jedoch die Biomechanik des Fußes ganz anders als beim Gehen aus, oder anders gesagt: Der Fuß auf dem Fahrrad bewegt sich anders als beim Gehen, weil auf dem Fahrrad die Zehen wenig belastet werden. Deshalb verteilt sich die Kraft, die vom Bein kommt, anders, und sie kann nicht an der Spitze des Fußes, sondern im oberen Bereich des zweiten Metatarsalknochen am besten befreit werden und ihre Wirkung auf dem Pedal am stärksten ausüben (vgl. auch dazu Gregersen et al., 2006). Daher ist es empfohlen, nicht mit der Spitze des Fußes auf dem Pedal zu drücken, sondern mit diesem Bereich. Für Schuhe mit Bindungen sollten dann die Bindungen am meisten in die Richtung vom Absatz gerückt werden, damit der Fuß und das Bein seine optimale Wirkung auf dem Pedal ausüben kann. Dabei werden auch Krampfen am Fuß vermieden, und dabei wir die Bedingung für einen optimalen Winkel des Fußes im Verhältnis zur Tibia von 122° (+-3°) in der Drei-Uhr-Position des Pedals erreicht (dazu vgl. Bini et al., 2016).

Am Fuß kann noch die Rotation des Fußes auf dem Pedal anhand von der Bindung am besten geregelt werden. Dabei muss berücksichtigt werden, dass der Fuß natürlich bewegt werden kann bzw. nicht zu stark nach innen oder nach draußen schaut. Bei unterschiedlichen Beinlängen können auch spezielle Sohlen für Fahrradschuhe gekauft werden oder Platten auf der Bindung montiert werden, die Unregelmäßigkeiten beim Pedalieren ausgleichen, selbst wenn Menschen asymmetrisch sind und solche Unregelmäßigkeiten nicht endgültig gelöst werden können.

Wenn die Fußposition steht, kann es zum Knie und zum Sattel gehen.

*** Knie und Sattel

Im Bereich von Knie und Sattel bzw. Hüfte finden wir die meisten Studien, die sich mit dem Bike-Fitting beschäftigen, weil dort die meisten Schmerzen entstehen, die das Fahrradfahren verursacht, wenn die Position des Fahrers auf dem Fahrrad falsch ist. Hier finden wir auch die meisten Tipps und Tricks, die auf dem Internet zirkulieren, um den Fahrern eine Idee zu geben, wie sie ihre Position auf dem Sattel am besten erreichen.

Ein erster Tipp ist, den Absatz auf dem Pedal zu legen, wenn sich das Pedal in der Sechs-Uhr-Position (unten) sich befindet. In dieser Position sollte das Bein leicht gestreckt sein, und es sollte immer noch möglich sein, rückwärts mit dem Absatz stets auf dem Pedal zu pedalieren. Dann wäre die Sattelhöhe optimal.

Ein zweiter Tipp, dass ebenfalls sehr verbreitet ist, verwendet ein Lot. Die Schnur muss in der Mitte der Kniescheibe gehalten werden, und sie soll -- da unterscheiden sich die Meinungen -- entweder durch die Mitte der Pedalachse, oder an der Schnittstelle zwischen dem Ende des Mittelfußknochen und dem Anfang vom Grundglied des kleineren Zehs gehen. Selbst wenn diese Tips eine grobe Schätzung der Position des Knies und des Knöchels mit Fuß auf dem Pedal wiedergeben können, sind sie sehr ungenau und manchmal führen sie zu falschen Ergebnissen je nachdem, wie lang oder kurz das Bein des Fahrers ist.

Bini (Bini et al., 2010) haben gezeigt, dass eine Verschiebung von einigen Milimetern der Sattelhöhe das Fahrradfahren signifikant beeinflussen bzw. verändern kann, und sie führt zu einer Verteilung der Kraft, die im Fall von einer falschen Sattelhöhe verschwendet wird. Menard hat ebenfalls erklärt, dass die Sattelhöhe mit der Position des Sattels entweder nach vorne oder nach hinten im Verhältnis zur Mitte des Sattelsrohrs so korreliert, dass eine falsche Sattelhöhe mechanisch zu einer falschen Position des Sattels (zu stark nach vorne oder zu stark nach hinten) führt (Menard et al., 2018). Daraus resultieren einerseits Knieschmerzen und andererseits Rücken- und Nackenschmerzen, die bis 60% der Schmerzen ausmachen, darunter Fahrradfahrer leiden. Davon sind am meisten nicht professionelle Fahrradfahrer betroffen, die mit einem Fahrrad weniger als erfahrene Fahrer unterwegs sind (vgl. etwa Mellion, 1991).

Deshalb sind präzise Messungen vom Bein und Beinwinkel auf dem Fahrrad wichtig, damit die Sattelhöhe und die Position des Sattels auf dem Sattelrohr optimal geschätzt werden kann. Am besten sollte auch dazu die Müdigkeit des Fahrers berücksichtigt werden, weil sich mit der Zeit auf dem Fahrrad und die davon verursachte Körpermüdigkeit die Position des Fahrers auf dem Fahrrad verändert wird.

Eine solche optimale Schätzung der Sattelhöhe und der Position des Sattels auf dem Sattelrohr kann nur durch Experimente mit möglichst vielen Fahrradfahrern durchgeführt werden, die während ihres Training auf einem Fahrrad-Heimtrainer gemessen werden, damit die Winkel vom Knöchel, Knie und Hüfte dynamisch und statisch im Verhältnis zur Sattelhöhe und zur Position des Sattels auf dem Sattelrohr ermittelt werden können. Die Studie von Bini und Hume (Bini und Hume, 2016) ist deshalb sehr interessant, weil sie ein solches Experiment durchführt und zum Ergebnis kommt, dass optimale Winkel berechnet werden können, um die optimale Position der Sattelhöhe zu ermitteln, die sowohl dynamisch als auch statisch gelten. Diese Winkel sind die Folgenden:

  - 38° (Innenwinkel) für Hüfte im Verhältnis zum Oberschenkelknochen
  - 62° (Außenwinkel) oder 28° (Innenwinkel) für Knie im Verhältnis zum Oberschenkelknochen
  - 122° (Innenwinkel) für Fuss im Verhältnis zur Tibia

Diese Winkel müssen mit einer Toleranzmessung von +- 1-3° berrücksichtigt werden, da je nach Bein und Bewegung diese Winkel leicht variieren können. In der Nachfolge dieser Arbeit hat Gatti eine allgemeine Formel zur Schätzung der optimalen Sattelhöhe ermittelt, die diese Winkel am besten abbildet, und die deshalb in der Fitoride App verwendet wird. Diese Formel verwendet zwei Messungen:

  - Messung vom Innenbein des Fahrers/der Fahrerin in Zentimetern
  - Messung des Winkels vom Sattelrohr zu einer Gerade in Grad

Entsprechend werden diese Messungen in die folgende Formel eingespeist: 7,41 + (0.82*Innennaht) - 0.1(Kineinnenwinkel im Verhältnis zum Oberschenkelknochen) + 0.003(Innennaht*Winkel vom Sattelrohr zu einer Gerade). Geben wir ein Beispiel. Für ein Fahrer, der eine Innenbeinlänge von 83,4 Zentimeter hat und ein Fahrrad mit einem Winkel des Sattelrohrs zur Gerade von 19,4 °, dann ergeben sich folgende Werte:

  - 7,41 + (0.82*83,4) = 7,41 + 68,388 = 75,798
  - 0.1*28° = 2,8
  - 0.003 * (83,4*19,4°) =0.003 * 1617,96 = 4,85388
  - Ergebnis: 75,798 - 2,8 + 4,85388 = 77,85188 cm

Die optimale Sattelhöhe von einem Fahrradfahrer mit diesen Massen ist dann 77,85 Zentimter hoch von der Kurbelachse bis an der Spitze der Sattelmitte. In dieser Position und im Einverständnis mit den erwähnten Studien wird die optimale Sitzposition für diesen Fahrer erreicht bzw. die Position, die eine optimale Verteilung der Kraft beim Fahrradfahren erlaubt. Da diese Position die optimale Position vom Fahrer auf dem Fahrrad ist, kann dann die Position des Sattels ermittelt werden, dessen Mitte mit der Mitte des Sattelrohrs in dieser Position übereinstimmen muss. Menard (Menard et al., 2018) hat in seiner Studie gezeigt, dass der Sattel nach vorne ungefähr bis zum Gravitationszentrum des Sattels (~2/3 der Sattellänge) gerückt werden könnte, ohne dass dabei Beschwerden insb. in den Knien beim Fahrer entstehen. Die Position des Fahrers ist "aggressiver" und die Kraft beansprucht die Quadriceps-Muskeln des Beines mehr, ohne das jedoch die Studien einen bedeutsamen Durchschnittsgewinn im Sinne einer erhöhten Geschwindigkeit im Vergleich zur Position der Sattelmitte in der Mitte des Sattelsrohrs für eine vergleichbare Fahrt von 20 Minuten verzeichnen. Dagegen generiert eine Position des Sattels zu weit nach hinten Schmerzen besonders im unteren Bereich des Rückens, die bei unerfahrenen Fahrern selbst nach einer kurzen Fahrt entstehen können. Schließlich sollte der Sattel parallel zum Boden eingestellt werden. Eine "aggressivere" Position vom Sattelwinkel mit einer Winkel leicht nach unten (1-2°) ist jedoch für erfahrene Fahrradfahrer ohne Bedenken zulässig, selbst wenn diese Position keine Vorteil im Sinne der Verteilung der Kraft auf dem Fahrrad oder der erhöhten Geschwindigkeit bringt.

Mit diesen Messungen steht das Bike-Fitting vom unteren Körperbereich, und das Bike-Fitting vom oberen Körperbereich kann vorgenommen werden.

*** Arm, Rücken und Lenker

Wenn die Position des Sattels steht, dann ergibt sich an der Hüfte ein optimaler Innenwinkel von 38° (1-3°), der die Position des Rückens auf dem Fahrrad im Verhältnis zur Distanz von der Mitte des Sattels bis zur Mitte der Lenkerstange des Fahrrads bestimmt. Wenn wir von Fahrrädern sprechen, die wie Citybike, Mountainbike, Gravelbike oder Rennräder sowohl für sportliche Tätigkeiten als auch als Verkehrsmittel verwendet werden, dann sollte die Position von Fahrern auf dem Fahrrad nach vorne gebogen sein, bis die Mitte der Hände den Lenker erreichen. Die erwähnten Studien zeigen in dieser Hinsicht, dass für eine optimale Sitzposition auf dem Fahrrad die Biegung des Rückens im Verhältnis zum Oberschenkelbein 80° (1-5°) ist, und dass die Position der Arme mit Händen auf dem Lenker einen Winkel von 30° (1-5°) im Verhältnis zum Boden zeigen sollte. Dies bedeutet das der Innenwinkel zwischen Rücken und Boden 45° (1-5°) betragen sollte (Bini et al., 2014).

Diese optimalen Messungen von Winkeln erlauben, sich die Position vom Rücken und von den Armen am Lenkrad in der Form von einem Dreieck vorzustellen, dessen Längen einerseits die Länge von der Sattelmitte bis zum Mittelpunkt des Lenkrads, andererseist vom Mittelpunkt des Lenkrads zum Schulterhauptgelenk, und schließlich vom Schulterhauptgelenk zum Oberschenkelbein ist. Die Winkel von einem solchen Dreieck können nach der üblichen Formel der Winkel von einem Dreieck ermittelt werden. Wenn der Winkel alpha zwischen Rücken und Oberrschenkelbein 45° (1-5°) und der Winkel beta zwischen Armen und Boden 30° (1-5°) betragen, dann beträgt der Winkel gamma zwischen Schulter und Rücken 105° (1-5 °). Mit einfachen Formeln der Trigonometrie können dann die Länge Lenker-Schulterhauptgelenk und Schulterhauptgelenk-Oberschenkelbein wie folgt ermittel werden:

  - Länge Sattelmitte bis Mittelpunkt des Lenkers = a
  - Länge Lenker-Schulterhauptgelenk = a/sin(gamma)*sin(alpha)
  - Länge Schulterhauptgelenk-Oberschenkelbein = a/sin(gamma)*sin(beta)

Nehmen wir ein Beispiel. Bei einer Länge a zwischen der Sattelmitte zum Mittelpunkt der Lenkerstange von 64,3 Zentimeter ergibt sich:

  - die Länge Lenker-Schulterhauptgelenk: 64,3/sin(105)*sin(45) = 47,07 Zentimeter
  - die Länge Schulterhauptgelenk-Oberschenkelbein: 64,3/sin(105)*sin(30) = 33,28 Zentimeter

Bei einer "race" bzw. aggressiveren Position (mehr Biegung) können diese Länge wie folgt variieren:

  - die Länge Lenker-Schulterhauptgelenk: 64,3/sin(110)*sin(40) = 43,98 Zentimeter
  - die Länge Schulterhauptgelenk-Oberschenkelbein: 64,3/sin(110)*sin(25) = 28,91 Zentimeter

Bei einer Position zur entspannten Tour (weniger Biegung) können diese Länge wie folgt variieren:

  - die Länge Lenker-Schulterhauptgelenk: 64,3/sin(100)*sin(50) = 50,02 Zentimeter
  - die Länge Schulterhauptgelenk-Oberschenkelbein: 64,3/sin(100)*sin(35) = 37,45 Zentimeter

An diesem Beispiel würde dann Fahrern empfehlen, die auf dem Fahrrad zu tief gebogen sind, den Vorbau am Lenker für einen kürzeren Vorbau zu wechseln. Symmetrisch geht es für Fahrer, die sich nicht tief genug auf dem Fahrrad fühlen und entsprechend den Vorbau am Lenker für einen größeren Vorbau wechseln sollten. Es muss aber hingewiesen werden, dass im Regelfall der Vorbau nicht weniger als 6 Zentimeter sein sollte, um Schwierigkeiten beim drehen zu vermeiden. Ebenfalls und für den selben Grund sollte er nicht größer als 12 Zentimeter sein.

Die hier berechneten Längen stimmen nicht mit der Armlänge bzw. Rückenlänge überein. Dies kommt daher, dass die Arme auf dem Fahrrad nicht ganz gestreckt werden müssen sowie die Schulter nicht nach vorne gehen sollten, damit das Fahrradfahren bequem und biomechanisch ebenfalls effizient erfolgt.

** Fazit

Aus der Literatur zum Bike-Fitting lassen sich Messmethoden verdichten, die zu einem unkomplizierten Bike-Fitting mit wenigen Mitteln führen, das in der Lage ist, zuverlässige Werte für die präzise Schätzung der Position vom Fahrer auf dem Fahrrad zu ermitteln. Diese Ergebnisse werden in der Form von einer Anwendung und einer App, die zu Hause oder on-the-go von jedem Fahrradfahrer und von jeder Fahrradfahrerin ab 15 Jahren gebraucht werden können, um ihre ideale Position zu erreichen und sowohl bequemer als auch effizienter auf ihrem Fahrrad unterwegs zu sein. Die Anwendung wird in der Sprache Python und die App mit GDScript geschrieben. Anwendung und App werden kostenfrei auf Github für Windows, Mac, Linux und für Smartphone (IOS, Android) angeboten.

** Quellen

- Bailey, M. P., Maillardet, F. J., Messenger, N. (2003). "Kinematics of cycling in relation to anterior knee pain and patellar tendinitis", /Journal of sports sciences/, 21(8), 649–657. https://doi.org/10.1080/0264041031000102015
- Bini, R. R., Tamborindeguy, A.C., Mota, C.B. (2010). "Effects of saddle height, pedaling cadence, and workload on joint kinetics and kinematics during cycling", /Journal of Sport Rehabilitation/, 19(3): 301-314.
- Bini, R., Hume, P., Kilding, A. (2014). "Optimizing Bicycle Configuration and Cyclists’ Body Position to Prevent Overuse Injury Using Biomechanical Approaches" in Bini, R., Carpes, F., /Biomechanics of Cycling/, New York: Springer, 92-107, doi: 10.1007/978-3-319-05539-8_8.
- Bini, R., Hume, P.. (2016). "A Comparison of Static and Dynamic Measures of Lower Limb Joint Angles in Cycling: Application to Bicycle Fitting", /Human Movement/, 17. 36-42. 10.1515/humo-2016-0005
- Blair, S. N., Cheng, Y., & Holder, J. S. (2001). "Is physical activity or physical fitness more important in defining health benefits?", /Medicine and science in sports and exercise/, 33(6 Suppl), S379–S420. https://doi.org/10.1097/00005768-200106001-00007
- Bourne, J. E., Sauchelli, S., Perry, R., Page, A., Leary, S., England, C., and Cooper, A. R. (2018). "Health benefits of electrically-assisted cycling: a systematic review", /The international journal of behavioral nutrition and physical activity/, 15(1), 116. https://doi.org/10.1186/s12966-018-0751-8
- Bundesministerium für Digitales und Verkehr, 2021, "Klimaschutz im Verkehr – Rad- und Fußverkehr", https://bmdv.bund.de/SharedDocs/DE/Artikel/G/Klimaschutz-im-Verkehr/klimaschutz-rad-und-fussverkehr.html (Zugriff am 17.04.2023).
- Bundesministerium für Verkehr und digitale Infrastruktur, 2021, "Fahrrad-Monitor Deutschland 2021", https://bmdv.bund.de/SharedDocs/DE/Anlage/StV/fahrrad-monitor-2021.pdf?__blob=publicationFile (Zugriff am 17.04.2023).
- Callaghan, M. J. (2005). "Lower body problems and injury in cycling", /Journal of Bodywork and Movement Therapies/, 9(3): 226-236.
- Holliday, W., Fisher, J., Theo, R., Swart, J. (2017). "Static versus dynamic kinematics in cyclists: A comparison of goniometer, inclinometer and 3D motion capture", /European Journal of Sport Science/, 17. 1-14. 10.1080/17461391.2017.1351580.
- García-López, J., Díez-Leal, S., Ogueta-Alday, A., Larrazabal, J., Rodríguez-Marroyo, J.A. (2016). "Differences in pedalling technique between road cyclists of different competitive levels", /Journal of Sports Sciences/, 34(17), 1619-1626, DOI: 10.1080/02640414.2015.1127987
- Gatti, A.A., Keir, P.J., Noseworthy, M.D., Maly, M.R. (2022). "Equations to Prescribe Bicycle Saddle Height based on Desired Joint Kinematics and Bicycle Geometry", /European Journal of Sport Science/, 22:3, 344-353.
- Gregersen, C. S., Hull, M.L.,  Hakansson, N.A. (2006). "How changing the inversion/eversion foot angle affects the nondriving intersegmental knee moments and the relative activation of the vastii muscles in cycling", /Journal of Biomechanical Engineering/, 128(3): 391- 398
- Holliday, W., Theo, R., Fisher, J., Swart, J. (2019). "Cycling: joint kinematics and muscle activity during differing intensities", /Sports Biomechanics/, 22. 1-15. 10.1080/14763141.2019.1640279.
- Menard, M., Domalain, M., Decatoire, A., Lacouture, A. (2018). "Influence of saddle setback on knee joint forces in cycling", /Sports Biomechanics/, doi: 10.1080/14763141.2018.1466906
- Mellion M. B. (1991). "Common cycling injuries. Management and prevention", /Sports medicine/, 11(1), 52–70. https://doi.org/10.2165/00007256-199111010-00004
- Møller, N. C., Østergaard, L., Gade, J. R., Nielsen, J. L., & Andersen, L. B. (2011). "The effect on cardiorespiratory fitness after an 8-week period of commuter cycling--a randomized controlled study in adults", /Preventive medicine/, 53(3), 172–177. https://doi.org/10.1016/j.ypmed.2011.06.007
- Oja, P., Titze, S., Bauman, A., de Geus, B.,  Krenn, P., Reger-Nash, B., Kohlberger, T., 2011 "Health benefits of cycling: a systematic review", /Scandinavian Journal of Medicine & Science in Sports/, 21(4): 496-509; doi: 10.1111/j.1600-0838.2011.01299.x.
- Statistisches Bundesamt /Destatis/, 2022, "Fahrradfahren: Niederlande im EU-Vergleich ganz vorn", https://www.destatis.de/Europa/DE/Thema/Verkehr/Fahrrad.html (Zugriff am 17.04.2023).
- Statistisches Bundesamt /Destatis/, 2022, "Mobilitätsverhalten von Frauen und Männern", https://www.destatis.de/Europa/DE/Thema/Verkehr/Mobilitaet-Frauen-Maenner.html?nn=217548 (Zugriff am 17.04.2023)
- World Health Organisation. (2018). "Physical activity", https://www.who.int/news-room/fact-sheets/detail/physical-activity (Zugriff am 18.04.2023)
